"use client";

import { Copy, KeyRound, RotateCw, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { deskFetch } from "@/lib/api";

type Key = { key_id: string; name: string; prefix: string; created_at: string; last_used_at: string | null; revoked_at: string | null };
type Created = Key & { secret: string };

export function AgentApiPage() {
  const [keys, setKeys] = useState<Key[]>([]); const [name, setName] = useState("My assessment agent"); const [secret, setSecret] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setKeys(await deskFetch<Key[]>("/desk/agent-api-keys")); } catch (error) { setMessage(error instanceof Error ? error.message : "Keys could not be loaded."); } }
  useEffect(() => {
    let active = true;
    deskFetch<Key[]>("/desk/agent-api-keys").then((value) => { if (active) setKeys(value); }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : "Keys could not be loaded."); });
    return () => { active = false; };
  }, []);
  async function create() { try { const value = await deskFetch<Created>("/desk/agent-api-keys", { method: "POST", body: JSON.stringify({ name }) }); setSecret(value.secret); setMessage("Copy this secret now. It will not be shown again."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Key could not be created."); } }
  async function action(id: string, verb: "revoke" | "rotate") { try { const value = await deskFetch<Created | Key>(`/desk/agent-api-keys/${id}/${verb}`, { method: "POST" }); if ("secret" in value) setSecret(value.secret); setMessage(verb === "rotate" ? "The old key was revoked. Copy the new secret now." : "Key revoked."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Key action failed."); } }
  return <div className="policy-guide-grid">
    <section className="panel"><div className="policy-warning"><ShieldCheck/><div><strong>Read-only boundary</strong><p>This endpoint returns a deterministic assessment using the workspace Candidate Assessment settings. A pass is not approval, an order intent, or permission to trade. Paper-only controls and human approval remain required.</p></div></div><h2>For an external agent</h2><p>Call <code>POST /api/v1/desk/strategy-assessments</code> with <code>X-AlphaDesk-API-Key</code>. Send the underlying, strategy type, legs, side, quantity, prices, Greeks and evidence timestamps.</p><p>The response includes <code>pass</code>, a <code>decision</code>, each check, failed check codes, actual values, limits, reasons, the policy snapshot and evidence expiry.</p><p>MCP exposes one tool, <code>assess_options_strategy</code>. Set <code>ALPHADESK_API_URL</code> and <code>ALPHADESK_API_KEY</code>. MCP forwards the request to AlphaDesk and does not contain separate risk logic.</p></section>
    <section className="panel"><h2>Agent API keys</h2><p>Keys are tied to this workspace. AlphaDesk stores only a cryptographic hash. The secret is displayed once when created or rotated.</p><label className="policy-field"><span><strong>Key name</strong><small>Use a name that identifies the agent.</small></span><input value={name} onChange={(event) => setName(event.target.value)} /></label><button onClick={() => void create()}><KeyRound size={15}/> Create key</button>{secret ? <div className="form-message" role="status"><strong>Copy once:</strong> <code>{secret}</code><button aria-label="Copy API key" onClick={() => void navigator.clipboard.writeText(secret)}><Copy size={14}/></button></div> : null}{message ? <p className="form-message" role="status">{message}</p> : null}<ul>{keys.map((key) => <li key={key.key_id}><strong>{key.name}</strong> <code>{key.prefix}...</code> {key.revoked_at ? <span>revoked</span> : <><button onClick={() => void action(key.key_id, "rotate")}><RotateCw size={14}/> Rotate</button><button onClick={() => void action(key.key_id, "revoke")}><Trash2 size={14}/> Revoke</button></>}</li>)}</ul></section>
    <section className="panel" aria-labelledby="assessment-response-heading"><h2 id="assessment-response-heading">What the assessment returns</h2><p>AlphaDesk returns more than a pass or fail result:</p><ul><li><code>PASS</code>, <code>FAIL</code> or <code>UNAVAILABLE</code> as the decision</li><li>an assessment ID and strategy identity</li><li>one result for each check, with the actual value, limit and reason</li><li>failed check codes so an agent can explain the result</li><li>the policy snapshot and policy version used</li><li>market evidence, observation and expiry times</li></ul><h3>Assessment score and scanner score</h3><p>The Agent API and MCP tool do not currently return the Market Scanner signal score. The scanner score is shown in the Market Scanner and Candidate Assessment pages. Exposing that score to an agent would need a separate API change.</p></section>
    <section className="panel" aria-labelledby="profile-settings-heading"><h2 id="profile-settings-heading">Changing the assessment profile</h2><p>You can change the workspace profile in the Candidate Assessment page. The available profiles are Very Conservative, Conservative, Fair, Aggressive and Very Aggressive.</p><ol><li>Open Candidate Assessment from the workspace navigation.</li><li>Select the profile you want.</li><li>Review the settings and save the change.</li></ol><p>The read-only Agent API and MCP tool cannot change the profile. They use the profile already saved for the workspace. A profile change affects later assessments and candidate discovery. Existing approvals still need review and execution-time revalidation.</p></section>
    <section className="panel" aria-labelledby="agent-instructions-heading"><h2 id="agent-instructions-heading">How to call the assessment</h2><h3>For a user</h3><ol><li>Create an Agent API key for this workspace and copy the secret once.</li><li>Give the endpoint, key header and strategy evidence to your agent.</li><li>Ask the agent to report the decision, failed checks, reasons and expiry.</li><li>Use the web pages to review the scanner score, profile and any trade approval.</li></ol><h3>For an AI agent</h3><p>Send a JSON request with the required strategy evidence. A request has this shape:</p><pre><code>{JSON.stringify({ underlying_symbol: "SPY", strategy_type: "DEFINED_RISK_SPREAD", side: "buy", quantity: 1, limit_price: "1.25", legs: "[option legs with quotes, liquidity and Greeks]", max_loss: "125", greeks: "[strategy Greeks]", market_evidence_at: "ISO-8601 timestamp", observed_at: "ISO-8601 timestamp", expires_at: "ISO-8601 timestamp" }, null, 2)}</code></pre><p>Use the returned checks to explain the result. Do not treat <code>PASS</code> as approval or permission to trade.</p></section>
    <section className="panel" aria-labelledby="safety-heading"><h2 id="safety-heading">What the agent cannot do</h2><p>The assessment API and MCP tool cannot:</p><ul><li>change the workspace profile</li><li>approve a trade</li><li>create or submit an order</li><li>bypass Guardian, broker, account, expiry or data checks</li><li>enable live trading</li></ul><p>Every assessment remains paper-only, requires human approval and has <code>execution_allowed: false</code>.</p></section>
  </div>;
}